/**
 * Gövde metni İngilizce'ye çevrilmiş sayfalar.
 *
 * NEDEN BİR LİSTE VAR. Bir doküman sitesinde en kolay yalan, çevrilmemiş bir
 * sayfayı öteki dilde sessizce göstermektir: okuyucu İngilizce bir menüden
 * girer, Türkçe bir sayfa bulur ve sitenin bozuk olduğunu düşünür. Liste bu
 * durumu GÖRÜNÜR kılıyor — çevrilmemiş sayfa bunu kendisi söylüyor.
 *
 * Ve liste bir hatırlatıcı değil, bir GATE'in girdisi: `check-docs-i18n.mjs`
 * burada yazan her sayfada gerçekten iki dilli bir `T` bloğu olduğunu
 * doğruluyor. Buraya bir slug eklemek, çeviriyi yazmadan mümkün değil.
 */
export const TRANSLATED: readonly string[] = [
  "accordion",
  "alert",
  "avatar",
  "avatar-stack",
  "badge",
  "beacon",
  "breadcrumb",
  "button",
  "card",
  "checkbox",
  "code",
  "combobox",
  "date-picker",
  "descriptions",
  "dialog",
  "dot",
  "dropdown-menu",
  "empty-blank",
  "empty-note",
  "empty-state",
  "empty-tile",
  "error-state",
  "field",
  "file-upload",
  "physics",
  "icon-button",
  "input",
  "kbd",
  "kpi",
  "installation",
  "label",
  "line-chart",
  "pie-chart",
  "bar-chart",
  "link",
  "list-row",
  "live-scope",
  "locale-switcher",
  "log-view",
  "logo-tile",
  "mini-button",
  "multi-select",
  "tree-select",
  "rich-text",
  "tokens",
  "tailwind",
  "icons",
  "new-panel",
  "appearance",
  "blocks",
  "templates",
  "list-screen",
  "number-input",
  "page-band",
  "pagination",
  "password-input",
  "popover",
  "progress",
  "radio-group",
  "rail-link",
  "rise",
  "says-bubble",
  "schedule-input",
  "score-matrix",
  "score-meter",
  "score-ring",
  "scroll-x",
  "secret-field",
  "section-head",
  "segmented",
  "select",
  "selection-bar",
  "separator",
  "sheet",
  "skeleton",
  "slider",
  "sort-header",
  "sparkline",
  "spinner",
  "status-chip",
  "steps",
  "surface",
  "swap",
  "switch",
  "table",
  "tabs",
  "tags-input",
  "theme",
  "textarea",
  "theme-toggle",
  "timeline-strip",
  "toast",
  "tooltip",
];

export function isTranslated(slug: string): boolean {
  return TRANSLATED.includes(slug);
}
